# yaml-language-server: $schema=https://raw.githubusercontent.com/iterative/dvcyaml-schema/master/schema.json
stages:

  clean_fire_data:
    cmd: python pipelines/clean_fire_data.py
    deps:
      - data/raw/fire_archive_SV-C2_607788.csv
      - data/raw/cb_2023_us_state_20m.zip
      - pipelines/clean_fire_data.py
    outs:
      - data/interim/fire_clean.csv:
          cache: true
          persist: true

  preprocess_fire_data:
    cmd: python pipelines/preprocess_fire_data.py
    deps:
      - data/interim/fire_clean.csv
      - pipelines/preprocess_fire_data.py
    outs:
      - data/processed/california_wildfires.csv:
          cache: true
          persist: true

  clean_weather_data:
    cmd: python pipelines/clean_weather_data.py --all-years 
    deps:
      - pipelines/clean_weather_data.py
    outs:
      - data/interim/weather_clean:
          cache: true
          persist: true
      - data/interim/weather_master.parquet:
          cache: true
          persist: true

  feature_engineering_weather:
    cmd: python pipelines/apply_weather_features.py
    deps:
      - data/interim/weather_master.parquet
      - pipelines/apply_weather_features.py
    outs:
      - data/interim/weather_features.parquet:
          cache: true
          persist: true

  merge_weather_fire:
    cmd: python pipelines/apply_merge_weather_fire.py
    deps:
      - data/processed/california_wildfires.csv
      - data/interim/weather_features.parquet
      - pipelines/apply_merge_weather_fire.py
    outs:
      - data/processed/merged/merged_fire_weather.csv:
          cache: true
          persist: true



  # train_model:
  #   cmd: python pipelines/train_model.py
  #   deps:
  #     - data/processed/california_wildfires.csv
  #     - configs/params.yml
  #   outs:
  #     - artifacts/models/wildfire_model.pkl
  #   metrics:
  #     - artifacts/metrics/model_metrics.json:
  #         cache: false
