# yaml-language-server: $schema=https://raw.githubusercontent.com/iterative/dvcyaml-schema/master/schema.json
stages:

  clean_fire_data:
    cmd: python pipelines/clean_fire_data.py
    deps:
      - data/raw/fire_archive_SV-C2_607788.csv
      - data/raw/cb_2023_us_state_20m.zip
      - pipelines/clean_fire_data.py
    outs:
      - data/interim/fire_clean.csv:
          cache: true
          persist: true

  preprocess_fire_data:
    cmd: python pipelines/preprocess_fire_data.py
    deps:
      - data/interim/fire_clean.csv
      - pipelines/preprocess_fire_data.py
    outs:
      - data/processed/california_wildfires.csv:
          cache: true
          persist: true

  clean_weather_data:
    cmd: python pipelines/clean_weather_data.py --all-years 
    deps:
      - pipelines/clean_weather_data.py
    outs:
      - data/interim/weather_clean:
          cache: true
          persist: true
      - data/interim/weather_master.parquet:
          cache: true
          persist: true

  # feature_engineering_weather:
  #   cmd: python pipelines/feature_engineering_weather.py
  #   deps:
  #     - data/interim/weather_master.parquet
  #     - pipelines/feature_engineering_weather.py
  #   outs:
  #     - data/interim/weather_features.parquet:
  #         cache: true
  #         persist: true

  merge_weather_fire:
    cmd: python pipelines/apply_merge_weather_fire.py
    deps:
      - data/processed/california_wildfires.csv
      - data/interim/weather_master.parquet
      - pipelines/apply_merge_weather_fire.py
    outs:
      - data/processed/merged/merged_fire_weather.csv:
          cache: true
          persist: true



  train_xgboost_model:
    cmd: python pipelines/train_xgboost_model.py --config configs/params_xgboost.yml
    deps:
      - data/processed/california_wildfires.csv
      - configs/params_xgboost.yml
      - pipelines/train_xgboost_model.py
      - src/wildfire_prediction/models/xgboost_model.py
    outs:
      - artifacts/models/wildfire_xgboost_model.pkl:
          cache : true
          persist: true
    metrics:
      - artifacts/metrics/xgboost_model_metrics.json:
          cache: false
    plots:
      - artifacts/figures/feature_importance.png:
          cache: false
      - artifacts/figures/confusion_matrix.png:
          cache: false