name: wildfire_xgboost
channels:
  - conda-forge
channel_priority: flexible

dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - geopandas
  - shapely
  - utm
  - pyyaml
  - dvc
  - scipy
  - folium
  - gdal
  - fiona
  - pyproj
  - rasterio
  - xgboost
  - lightgbm
  - plotly
  - joblib
  - tqdm
  - memory_profiler
  - ipykernel
  - streamlit
  - pytest
  - black
  - flake8
  - jupyter
  - notebook
  - pre-commit
  - isort
  - pylint
  - pyarrow
  - fastparquet
  - pydantic
  - mlflow
  - optuna
  - shap
  - streamlit-folium
  - dvc-gdrive

pip:
  - dvc-gdrive==2.19.1
  - streamlit-folium==0.11.1