name: wildfire_prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=23.0
  - pandas=1.5.3
  - numpy=1.24.3
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - scikit-learn=1.2.2
  - geopandas=0.12.2
  - shapely=2.0.1
  - utm=0.7.0
  - pyyaml=6.0
  - dvc=2.58.2
  - scipy=1.10.1
  - folium=0.14.0
  - fiona=1.9.4
  - pyproj=3.5.0
  - rasterio=1.3.6
  - xgboost=1.7.5
  - lightgbm=3.3.5
  - plotly=5.14.1
  - joblib=1.2.0
  - tqdm=4.65.0
  - memory_profiler=0.61.0
  - ipykernel=6.22.0
  - pip:
      - dvc-gdrive==2.19.1
      - pytest==7.3.1
      - black==23.3.0
      - flake8==6.0.0
      - jupyter==1.0.0
      - notebook==6.5.4
      - pre-commit==3.3.1
      - isort==5.12.0
      - pylint==2.17.4
      - pyarrow==12.0.0
      - fastparquet==2023.4.0
      - pydantic==1.10.7
      - mlflow==2.3.1
      - optuna==3.1.1
      - shap==0.41.0