# Model hyperparameters

train:
  test_size: 0.2
  random_state: 42
  cv_folds: 5
  sample_data: true # For development/testing
  sample_size: 100000 # Number of samples to use

model:
  type: xgboost
  params:
    n_estimators: 200
    max_depth: 8
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    min_child_weight: 3
    gamma: 0.1
    scale_pos_weight: 10 # Helps with class imbalance
    objective: binary:logistic
    eval_metric: auc
    random_state: 42

feature_engineering:
  grid_size_km: 1
  drop_low_confidence: true
  log_transform_frp: true
  normalize_brightness: true
  feature_columns:
    - frp_log
    - brightness_normalized
    - vpdmax # Maximum vapor pressure deficit
    - tmax # Maximum temperature
    - ppt # Precipitation
    - grid_id # Spatial information
    - week # Temporal information