# Model hyperparameters

train:
  test_size: 0.2
  random_state: 42
  cv_folds: 5

model:
  type: random_forest
  params:
    n_estimators: 100
    max_depth: 20
    min_samples_split: 2
    min_samples_leaf: 1
    bootstrap: true
    random_state: 42

feature_engineering:
  grid_size_km: 1
  drop_low_confidence: true
  log_transform_frp: true
  normalize_brightness: true
  feature_columns:
    - frp_log
    - brightness_normalized
    - confidence_encoded
    - is_day
    - month
    - day_of_year